/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing MediaInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MediaInformationTests
    {
        // TODO uncomment below to declare an instance variable for MediaInformation
        //private MediaInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaInformation
            //instance = new MediaInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaInformation
        /// </summary>
        [Test]
        public void MediaInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MediaInformation
            //Assert.IsInstanceOfType<MediaInformation> (instance, "variable 'instance' is a MediaInformation");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'FileFormat'
        /// </summary>
        [Test]
        public void FileFormatTest()
        {
            // TODO unit test for the property 'FileFormat'
        }
        /// <summary>
        /// Test the property 'FileFormatFull'
        /// </summary>
        [Test]
        public void FileFormatFullTest()
        {
            // TODO unit test for the property 'FileFormatFull'
        }
        /// <summary>
        /// Test the property 'ValidFileFormats'
        /// </summary>
        [Test]
        public void ValidFileFormatsTest()
        {
            // TODO unit test for the property 'ValidFileFormats'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'BitRate'
        /// </summary>
        [Test]
        public void BitRateTest()
        {
            // TODO unit test for the property 'BitRate'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

    }

}
