/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing NsfwResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NsfwResultTests
    {
        // TODO uncomment below to declare an instance variable for NsfwResult
        //private NsfwResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NsfwResult
            //instance = new NsfwResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NsfwResult
        /// </summary>
        [Test]
        public void NsfwResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NsfwResult
            //Assert.IsInstanceOfType<NsfwResult> (instance, "variable 'instance' is a NsfwResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'HighestClassificationResult'
        /// </summary>
        [Test]
        public void HighestClassificationResultTest()
        {
            // TODO unit test for the property 'HighestClassificationResult'
        }
        /// <summary>
        /// Test the property 'HighestScore'
        /// </summary>
        [Test]
        public void HighestScoreTest()
        {
            // TODO unit test for the property 'HighestScore'
        }
        /// <summary>
        /// Test the property 'TotalRacyFrames'
        /// </summary>
        [Test]
        public void TotalRacyFramesTest()
        {
            // TODO unit test for the property 'TotalRacyFrames'
        }
        /// <summary>
        /// Test the property 'TotalNsfwFrames'
        /// </summary>
        [Test]
        public void TotalNsfwFramesTest()
        {
            // TODO unit test for the property 'TotalNsfwFrames'
        }
        /// <summary>
        /// Test the property 'TotalFrames'
        /// </summary>
        [Test]
        public void TotalFramesTest()
        {
            // TODO unit test for the property 'TotalFrames'
        }
        /// <summary>
        /// Test the property 'NsfwScannedFrames'
        /// </summary>
        [Test]
        public void NsfwScannedFramesTest()
        {
            // TODO unit test for the property 'NsfwScannedFrames'
        }

    }

}
