/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing NsfwScannedFrame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NsfwScannedFrameTests
    {
        // TODO uncomment below to declare an instance variable for NsfwScannedFrame
        //private NsfwScannedFrame instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NsfwScannedFrame
            //instance = new NsfwScannedFrame();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NsfwScannedFrame
        /// </summary>
        [Test]
        public void NsfwScannedFrameInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NsfwScannedFrame
            //Assert.IsInstanceOfType<NsfwScannedFrame> (instance, "variable 'instance' is a NsfwScannedFrame");
        }


        /// <summary>
        /// Test the property 'FrameNumber'
        /// </summary>
        [Test]
        public void FrameNumberTest()
        {
            // TODO unit test for the property 'FrameNumber'
        }
        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Test]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'ClassificationResult'
        /// </summary>
        [Test]
        public void ClassificationResultTest()
        {
            // TODO unit test for the property 'ClassificationResult'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
