/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing SplitVideoResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SplitVideoResultTests
    {
        // TODO uncomment below to declare an instance variable for SplitVideoResult
        //private SplitVideoResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SplitVideoResult
            //instance = new SplitVideoResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SplitVideoResult
        /// </summary>
        [Test]
        public void SplitVideoResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SplitVideoResult
            //Assert.IsInstanceOfType<SplitVideoResult> (instance, "variable 'instance' is a SplitVideoResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Test]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }

    }

}
