/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing StillFramesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StillFramesResultTests
    {
        // TODO uncomment below to declare an instance variable for StillFramesResult
        //private StillFramesResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StillFramesResult
            //instance = new StillFramesResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StillFramesResult
        /// </summary>
        [Test]
        public void StillFramesResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StillFramesResult
            //Assert.IsInstanceOfType<StillFramesResult> (instance, "variable 'instance' is a StillFramesResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'TotalFrames'
        /// </summary>
        [Test]
        public void TotalFramesTest()
        {
            // TODO unit test for the property 'TotalFrames'
        }
        /// <summary>
        /// Test the property 'StillFrames'
        /// </summary>
        [Test]
        public void StillFramesTest()
        {
            // TODO unit test for the property 'StillFrames'
        }

    }

}
