/* 
 * videoapi
 *
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Api;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Model;
using Cloudmersive.APIClient.NET.VideoAndMediaServices.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.VideoAndMediaServices.Test
{
    /// <summary>
    ///  Class for testing VideoFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VideoFileTests
    {
        // TODO uncomment below to declare an instance variable for VideoFile
        //private VideoFile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VideoFile
            //instance = new VideoFile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VideoFile
        /// </summary>
        [Test]
        public void VideoFileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VideoFile
            //Assert.IsInstanceOfType<VideoFile> (instance, "variable 'instance' is a VideoFile");
        }


        /// <summary>
        /// Test the property 'VideoNumber'
        /// </summary>
        [Test]
        public void VideoNumberTest()
        {
            // TODO unit test for the property 'VideoNumber'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
